### ISSUE TITLE
Crash on error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by maltespence** [Infixo/CS2-InfoLoom#16] opened 2024-02-22 19:50 UTC
Had a crash with the following errorcode. Launching with Infoloom v 0.8.1 through Thunderstore.

```
Object reference not set to an instance of an object
NullReferenceException: Object reference not set to an instance of an object
  at Unity.Entities.ComponentLookup`1[T].get_Item (Unity.Entities.Entity entity) [0x00032] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at InfoLoom.WorkplacesInfoLoomUISystem+CalculateWorkplaceDataJob.Execute (Unity.Entities.ArchetypeChunk& chunk, System.Int32 unfilteredChunkIndex, System.Boolean useEnabledMask, Unity.Burst.Intrinsics.v128& chunkEnabledMask) [0x00103] in <f54d889d50924f69b900b09781e8cd29>:0 
  at InfoLoom.WorkplacesInfoLoomUISystem+CalculateWorkplaceDataJob.Unity.Entities.IJobChunk.Execute (Unity.Entities.ArchetypeChunk& chunk, System.Int32 unfilteredChunkIndex, System.Boolean useEnabledMask, Unity.Burst.Intrinsics.v128& chunkEnabledMask) [0x00000] in <f54d889d50924f69b900b09781e8cd29>:0 
  at Unity.Entities.JobChunkExtensions+JobChunkProducer`1[T].ExecuteInternal (Unity.Entities.JobChunkExtensions+JobChunkWrapper`1[T]& jobWrapper, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x000b5] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.JobChunkExtensions+JobChunkProducer`1[T].Execute (Unity.Entities.JobChunkExtensions+JobChunkWrapper`1[T]& jobWrapper, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00000] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at (wrapper delegate-invoke) Unity.Entities.JobChunkExtensions+JobChunkProducer`1+ExecuteJobFunction[InfoLoom.WorkplacesInfoLoomUISystem+CalculateWorkplaceDataJob].invoke_void_JobChunkExtensions/JobChunkWrapper`1<T>&_intptr_intptr_JobRanges&_int(Unity.Entities.JobChunkExtensions/JobChunkWrapper`1<InfoLoom.WorkplacesInfoLoomUISystem/CalculateWorkplaceDataJob>&,intptr,intptr,Unity.Jobs.LowLevel.Unsafe.JobRanges&,int)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

**Comment by Infixo** [comment] 2024-02-23 20:55
Yeah... it happens unfortunately very rarely and I am not able to reproduce it. Do you remember anything specific about when this happened?
Also, on Discord someone reported that a crash happened after massive buldozing of homes. Maybe you also buldozed things?

It is a duplicate of https://github.com/Infixo/CS2-InfoLoom/issues/12 
I created a special version of the mod to test an improvement that might fix that. It is available in #12 
Maybe you can install it and see if the problem would go away?

**Comment by Infixo** [comment] 2024-02-24 15:50
Can you try this version?
[InfoLoomFix2.zip](https://github.com/Infixo/CS2-InfoLoom/files/14393400/InfoLoomFix2.zip)

**Comment by Infixo** [comment] 2024-02-24 15:52
Please see #17

**Closed as completed** 2024-04-13 13:51 UTC
Labels: duplicate
