### ISSUE TITLE
Possible bug [see #17]

### ISSUE THREAD

**Issue by joakgus** [Infixo/CS2-InfoLoom#12] opened 2024-02-12 20:25 UTC
Object reference not set to an instance of an object
NullReferenceException: Object reference not set to an instance of an object
  at Unity.Entities.ComponentLookup`1[T].get_Item (Unity.Entities.Entity entity) [0x00032] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at InfoLoom.WorkplacesInfoLoomUISystem+CalculateWorkplaceDataJob.Execute (Unity.Entities.ArchetypeChunk& chunk, System.Int32 unfilteredChunkIndex, System.Boolean useEnabledMask, Unity.Burst.Intrinsics.v128& chunkEnabledMask) [0x00103] in <f54d889d50924f69b900b09781e8cd29>:0 
  at InfoLoom.WorkplacesInfoLoomUISystem+CalculateWorkplaceDataJob.Unity.Entities.IJobChunk.Execute (Unity.Entities.ArchetypeChunk& chunk, System.Int32 unfilteredChunkIndex, System.Boolean useEnabledMask, Unity.Burst.Intrinsics.v128& chunkEnabledMask) [0x00000] in <f54d889d50924f69b900b09781e8cd29>:0 
  at Unity.Entities.JobChunkExtensions+JobChunkProducer`1[T].ExecuteInternal (Unity.Entities.JobChunkExtensions+JobChunkWrapper`1[T]& jobWrapper, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x000b5] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.JobChunkExtensions+JobChunkProducer`1[T].Execute (Unity.Entities.JobChunkExtensions+JobChunkWrapper`1[T]& jobWrapper, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00000] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at (wrapper delegate-invoke) Unity.Entities.JobChunkExtensions+JobChunkProducer`1+ExecuteJobFunction[InfoLoom.WorkplacesInfoLoomUISystem+CalculateWorkplaceDataJob].invoke_void_JobChunkExtensions/JobChunkWrapper`1<T>&_intptr_intptr_JobRanges&_int(Unity.Entities.JobChunkExtensions/JobChunkWrapper`1<InfoLoom.WorkplacesInfoLoomUISystem/CalculateWorkplaceDataJob>&,intptr,intptr,Unity.Jobs.LowLevel.Unsafe.JobRanges&,int)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Infixo** [comment] 2024-02-13 16:13
Does it repeat? Are you using 0.8.1?

**Comment by joakgus** [comment] 2024-02-13 18:24
Yeah, it repeats, and I have gotten on 0.8.0 and 0.8.1

**Comment by Infixo** [comment] 2024-02-14 00:18
You are the only one so far reporting that and I am pretty sure a lot of people are using the mod. I have no such issues, ofc. That must be some clash with some other mod most likely. What mods do you use?
I asked about 0.8.1 because in 0.8.0 someone reported similar issue and in 0.8.1 it was gone.
That is ComponentLookup failure which means that this function tries to read data that is not there. Does this issue happen when you open the window or just pops-up by itself? I assume a pop-up window appears with that error message - does it go away when you click Continue?

**Comment by joakgus** [comment] 2024-02-14 07:54
Dude, I use like 20 mods. 

It pops up by itself and it breaks the game. There is no continuing after it shows up. The reason why you guys have gotten it is because it doesn’t break right away but like an hour into the session. So maybe you don’t play long enough to experience it?

**Comment by Infixo** [comment] 2024-02-14 13:01
I play much longer than 1 hour use very few mods, maybe 5.
Can you please post the screenshot of your BepInEx plugin folder? I will try to replicate the issue.

**Comment by Infixo** [comment] 2024-02-14 16:34
[InfoLoom_fix12.zip](https://github.com/Infixo/CS2-InfoLoom/files/14283614/InfoLoom_fix12.zip)
@joakgus Please try the attached file. I added some extra checks.
There is a log user_directory\AppData\LocalLow\Colossal Order\Cities Skylines II\Logs\InfoLoom.log.
If the problem is solved then there should be entries like "Warning! Non-existing m_Property" or "Warning! Non-existing m_Prefab". However, the game should not crash.
If the game would still crash with this error above and there are no such entries, then the issue is somewhere else.
Please let me know about the results.

**Comment by Infixo** [comment] 2024-02-24 15:51
Please see #17

**Comment by khallmark** [comment] 2024-04-17 04:36
@Infixo should be able to close this :-D

**Comment by Infixo** [comment] 2024-04-20 11:02
Fixed in #22

**Closed as completed by Infixo** 2024-04-20 11:02 UTC
Labels: duplicate
